ckpt_root: ckpt
cuda: True
gpu: 1
num_workers: 8

dataset:
    name: PanoCorBonDataset
    train_kwargs:
        flag: train
        root_dir: /media/public_dataset/360Layout/mp3d
        flip: True
        rotate: True
        gamma: True
        stretch: True
    valid_kwargs:
        flag: valid
        root_dir: /media/public_dataset/360Layout/mp3d

training:
    epoch: 300
    batch_size: 4
    save_every: 10
    optim_lr: 0.0001
    optim_poly_gamma: 0.9

model:
    file: lib.model.hohonet
    modelclass: HoHoNet
    kwargs:
        emb_dim: 256
        backbone_config:
            module: Resnet
            kwargs:
                backbone: resnet34
        decode_config:
            module: EfficientHeightReduction
        refine_config:
            module: TransEn
            kwargs:
                position_encode: 256
                nhead: 8
                num_layers: 1
                dim_feedforward: 2048
        modalities_config:
            LayoutEstimator:
                cor_weight: 1.
                bon_weight: 1.
                last_bias: False
                last_ks: 1
