ckpt_root: ckpt
cuda: True
gpu: 0
num_workers: 8

dataset:
    name: MLCDataset
    train_kwargs:
        flag: train
        root_dir: /media/NFS/justin/retraining/mvl/train
        flip: True
        rotate: True
        gamma: True
        sampling: None
    valid_kwargs:
        flag: valid
        root_dir: /media/NFS/justin/retraining/mvl/pruned_test

training:
    epoch: 10
    batch_size: 5
    save_every: 1
    optim_lr: 0.0001
    optim_poly_gamma: 0.9

model:
    file: lib.model.hohonet
    modelclass: HoHoNet
    kwargs:
        emb_dim: 256
        backbone_config:
            module: Resnet
            kwargs:
                backbone: resnet34
        decode_config:
            module: EfficientHeightReduction
        refine_config:
            module: TransEn
            kwargs:
                position_encode: 256
                nhead: 8
                num_layers: 1
                dim_feedforward: 2048
        modalities_config:
            LayoutEstimator:
                cor_weight: 1.
                bon_weight: 1.
                last_bias: False
                last_ks: 1
